### PR TITLE
`grp2idx`: Improve `datatypes` integration and fix existing bugs

### LINKED ISSUE #324: Add support for `categorical`, `datetime`, and `duration` vectors in `grp2idx`
The `grp2idx` function currently requires `categorical`, `datetime`, and `duration` vector support to be compatible with the [MATLAB version](https://www.mathworks.com/help/stats/grp2idx.html) of `grp2idx`.

Expected behavior: Add compatibility for `categorical`, `datetime`, and  `duration`, handle edge cases and write extra BISTs and demos.

Note: I noticed that `crosstab` uses `grp2idx` internally so that would be a next logical step to integrate after this is resolved.

### PR DESCRIPTION
**Pull request by SergeantQuickscoper**
This PR does the following:
- Adds `duration`, `categorical` and `string` array support to `grp2idx`, and thereby closes #324.  Integration of `datetime`  is not included for now, and is the last step towards full MATLAB compatibility.
- Fixes a bug where `numerical` and `logical` arrays were not in sorted groups, which differred from MATLAB.
- Fixes a bug where `NaN` values in the middle of the array caused incorrect indices in the `g` array.
- Fixes most regressions in incorrect tests that occurred due `grp2idx` change, with the notable exception of `grpstats`.

**Note**: Currently, I believe there is a bug in in `cell`, as creation of empty cell arrays `0x1` and `1x0` currently just create empty cell arrays `0x0`. In MATLAB, `grp2idx` always returns `0x1` empty arrays for `gn` and `gl` arrays, when there exist no groups, and due to the aforementioned bug, `grp2idx` still returns `0x0` empty arrays when such cases arise.

Apologies for any formatting errors.

Don Roy Chacko <donisepic30@gmail.com>

### CODE REVIEW

File: inst/grp2idx.m [hunk 1]
```diff
@@ -147,3 +161,75 @@
 %!        {[1; 2; 1; 2; 2] {"sci"; "oct"} {"sci"; "oct"}});
 %!test assert (nthargout (1:3, @grp2idx, {"sa" "et" "et" "" "sa"}),
 %!        {[1; 2; 2; NaN; 1] {"sa"; "et"} {"sa"; "et"}})
+
+## test for categorical arrays
+%!test
+%! [g, gn, gl] = grp2idx(categorical({'low', 'med', 'high', 'low'}));
```
Comment (Sonu0305) [inline inst/grp2idx.m]: Coding style fixes
